import argparse
import os
import sys
import time

from ww.llm.openrouter_client import stream_openrouter_api


REFINE_RULE = """Refine a Raw Whisper Meeting Transcription into a Polished, Comprehensive Article

Context: You are given a raw transcription file generated by Whisper from a recorded meeting conversation. Whisper does NOT emit speaker labels — utterances from multiple speakers are interleaved with no markers. The text may also contain noise, broken sentences, filler words, code-switching, and recognition errors.

Task: Read the provided transcription and produce a refined Markdown article that captures the full discussion in comprehensive detail.

This is REFINEMENT, not summarization. Preserve every substantive point — restructure for clarity, but never condense or drop information. The output should typically be similar in length to the input (in words/characters), not dramatically shorter.

Requirements:

Content & Structure
- Start with a single H1 title that captures the core subject of the meeting.
- Immediately after the title, include a short summary paragraph (3–6 sentences) that introduces the main themes covered.
- Organize the body under H2 section headings driven by natural topic shifts in the discussion.
- Use H3 sub-headings within sections when a section covers multiple distinct sub-topics.
- Within sections, break content into focused paragraphs by topic — avoid walls of text and avoid one-sentence paragraphs.
- Use bullet lists when the speakers genuinely enumerate items (steps, options, pros/cons, named tools); use prose for explanations and narrative.

Detail Preservation (Critical)
- Do NOT summarize, simplify, or condense the discussion. Cover every meaningful point that was made.
- Preserve specific examples, anecdotes, numbers, names, dates, and technical details exactly as discussed.
- Preserve technical terms, proper nouns, product names, library names, frameworks, model names, company names, and specific references — do not generalize them away (e.g., do not turn "CUDA kernel" into "GPU code").
- Convert spoken numeric expressions to numerals: "fifty K CNY" → "50K CNY", "three hundred million" → "300 million", "two point five times" → "2.5x", "GPT four" → "GPT-4".
- If the speakers explore a tradeoff, list both sides. If they describe a process, describe each step. If they list considerations, list each one.
- If you find yourself about to write "and so on," "various topics," "many things were discussed," or "they covered different aspects" — stop and write out what was actually said.
- When the conversation discusses code, architecture, or technical workflows, retain the specifics: function names, file paths, command names, configuration values, version numbers.

Tone & Fidelity
- Preserve the original meaning, tone, speaking style, and emotional nuance.
- Do not overly formalize the content — retain the conversational and authentic feel of the original meeting.
- Keep moments of humor, frustration, hesitation, or excitement legible in the prose rather than scrubbing them out.
- If a sentence is unclear due to transcription quality, infer conservatively and preserve the ambiguity rather than inventing details. It is fine to write "(unclear)" in rare cases where meaning cannot be recovered.

Speaker Handling
- Whisper transcription has no speaker labels and you cannot reliably reconstruct who said what.
- Do NOT use labels like "Speaker A / Speaker B," "Person 1 / Person 2," or invent speaker names.
- Narrate the discussion in third person, using phrases like "they discussed," "both participants," "one participant noted," "it was raised that," "the group considered," "another argued."
- For clear question-and-answer dynamics, render as "one participant asked …; another responded that …" rather than guessing identities.

Noise Removal
- Remove transcription artifacts:
  - Filler words and verbal tics: "um," "uh," "like," "you know," "I mean," "kind of," "sort of," "basically," "literally," "right" (when not substantive), "yeah" (when not substantive)
  - False starts and self-corrections — keep only the corrected version
  - Repeated phrases and stutters
  - Obviously garbled fragments and Whisper recognition errors with no recoverable meaning
- Keep substantive uses of "yeah," "right," "exactly," etc. when they convey real agreement or are part of a quoted phrase that carries meaning.
- Do not remove information; only restructure it into clearer, shorter blocks.

Reorganization
- Merge fragmented dialogue across the transcript into coherent topical paragraphs — do NOT preserve original chronological order if topics are scattered. Group all discussion of the same topic together even if it was revisited later.
- Within each topic, follow the natural flow of the argument or explanation rather than the order utterances happened to appear.

Language
- Always output in fluent, natural English regardless of the source language.
- If the source is Chinese (or any other language), translate while refining — preserve meaning, nuance, technical terminology, and emotional register. Avoid stiff, word-for-word translation.
- Keep proper nouns, brand names, and technical terms in their canonical form (use "CUDA" not "kuda"; keep Chinese company names in their commonly used English form when one exists, otherwise transliterate).

Output Format
- Output ONLY valid Markdown content.
- Do NOT include any preamble ("Here is the refined article…"), closing remarks, metadata block, or commentary outside the article itself.
- Start the response directly with the H1 title.
"""


def _read_input(path):
    abs_path = os.path.abspath(path)
    if not os.path.isfile(abs_path):
        print(f"Error: file not found: {abs_path}")
        sys.exit(1)
    with open(abs_path, "r", encoding="utf-8") as f:
        return abs_path, f.read()


def _output_path(input_path):
    root, _ = os.path.splitext(input_path)
    return root + ".md"


def _build_prompt(transcript):
    return f"{REFINE_RULE}\n\n---\n\nTranscription:\n\n{transcript}"


def _stream_to_stdout(prompt, model, debug):
    chunks = []
    started = time.monotonic()
    first_chunk_at = None
    for text in stream_openrouter_api(prompt, model=model, debug=debug):
        if first_chunk_at is None:
            first_chunk_at = time.monotonic()
            print(
                f"[refine] first token in {first_chunk_at - started:.1f}s, streaming...\n"
            )
            print("---")
        sys.stdout.write(text)
        sys.stdout.flush()
        chunks.append(text)
    elapsed = time.monotonic() - started
    if first_chunk_at is None:
        print("[refine] warning: stream ended with no content")
    else:
        print("\n---")
    return "".join(chunks), elapsed


def main():
    parser = argparse.ArgumentParser(
        description="Refine a Whisper transcription txt file into a polished Markdown article via OpenRouter (streaming)."
    )
    parser.add_argument("input_file", help="Path to the .txt transcription file")
    parser.add_argument(
        "--model",
        default="deepseek/deepseek-v4-flash",
        help="OpenRouter model (default: deepseek/deepseek-v4-flash)",
    )
    parser.add_argument("--debug", action="store_true")
    args = parser.parse_args()

    input_path, transcript = _read_input(args.input_file)
    output_path = _output_path(input_path)
    prompt = _build_prompt(transcript)

    print(f"[refine] input={input_path} ({len(transcript)} chars)")
    print(f"[refine] output={output_path}")
    print(f"[refine] model={args.model}")
    print("[refine] connecting to OpenRouter...")

    refined, elapsed = _stream_to_stdout(prompt, args.model, args.debug)

    if not refined:
        print("[refine] no content received; not writing output file")
        sys.exit(1)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(refined)

    print(f"[refine] wrote {len(refined)} chars to {output_path} in {elapsed:.1f}s")
