import argparse
import os
import sys

from ww.llm.openrouter_client import call_openrouter_api


REFINE_RULE = """Refine a Raw Whisper Meeting Transcription into a Polished Article

Context: You are given a raw transcription file generated by Whisper from a recorded meeting conversation. The transcription may contain noise, broken sentences, filler words, and missing speaker labels.

Task: Read the provided transcription file and generate a new refined output file in Markdown format.

Requirements:

Content & Structure
- Rewrite and organize the content into a clean, readable article, meeting summary, or post.
- Add a suitable title at the top.
- Add section headings where appropriate to organize the content logically.
- Include a short summary paragraph at the very beginning (after the title).

Tone & Fidelity
- Preserve the original meaning, tone, speaking style, and emotional nuance as closely as possible.
- Do not overly formalize the content - retain the conversational and authentic feel of the original meeting.
- If some sentences are unclear due to transcription quality, infer conservatively and preserve ambiguity rather than inventing details.

Speaker Handling
- The original meeting involved two or more speakers, but speaker labels were lost during transcription.
- Do not attempt to reconstruct speaker identities or use labels like "Speaker A / Speaker B."
- Instead, narrate the discussion naturally from a third-person perspective, using phrases like "they," "both parties," "one participant noted," "it was discussed that," etc.

Noise Removal
- Remove obvious transcription artifacts, including:
  - Repeated filler words (e.g., "um," "uh," "like," "you know")
  - Broken or incomplete sentences with no recoverable meaning
  - Whisper recognition errors and garbled text

Reorganization
- Merge fragmented dialogue into coherent paragraphs.
- Group related discussion points under logical sections.

Output
- Output only valid Markdown content.
- The language of the output should match the language of the original transcription (e.g., if the meeting was in Chinese, output in Chinese; if in English, output in English).
"""


def _read_input(path):
    abs_path = os.path.abspath(path)
    if not os.path.isfile(abs_path):
        print(f"Error: file not found: {abs_path}")
        sys.exit(1)
    with open(abs_path, "r", encoding="utf-8") as f:
        return abs_path, f.read()


def _output_path(input_path):
    root, _ = os.path.splitext(input_path)
    return root + ".md"


def _build_prompt(transcript):
    return f"{REFINE_RULE}\n\n---\n\nTranscription:\n\n{transcript}"


def main():
    parser = argparse.ArgumentParser(
        description="Refine a Whisper transcription txt file into a polished Markdown article via OpenRouter."
    )
    parser.add_argument("input_file", help="Path to the .txt transcription file")
    parser.add_argument(
        "--model",
        default="deepseek/deepseek-v4-flash",
        help="OpenRouter model (default: deepseek/deepseek-v4-flash)",
    )
    parser.add_argument("--debug", action="store_true")
    args = parser.parse_args()

    input_path, transcript = _read_input(args.input_file)
    output_path = _output_path(input_path)
    prompt = _build_prompt(transcript)

    print(f"[refine] input={input_path}")
    print(f"[refine] output={output_path}")
    print(f"[refine] model={args.model}")

    refined = call_openrouter_api(prompt, model=args.model, debug=args.debug)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(refined)

    print(f"[refine] wrote {len(refined)} chars to {output_path}")
