import argparse
import os
import sys
import time

from ww.llm.openrouter_client import stream_openrouter_api


REFINE_RULE = """Refine a Raw Whisper Meeting Transcription into a Polished, Comprehensive Article

CRITICAL INSTRUCTION — This is the single most important paragraph in this entire prompt. Read it twice.

This is a REFINEMENT task, NOT a summarization task. Your #1 failure mode as a language model is condensing — collapsing 10 points into 3, replacing specific examples with vague summaries, turning a 5-minute nuanced explanation into two sentences. You must actively and continuously fight this tendency. The output MUST be approximately the SAME LENGTH as the input (within 85–115% of the input's word count). If the input is 5,000 words, your output should be 4,250–5,750 words — NOT 1,500 words. If you find your output is less than 80% of the input length, you are summarizing too aggressively. Go back and add the details you dropped.

QUANTITATIVE RULE: For every distinct speaker utterance in the input that contains substantive content (a claim, example, question, answer, argument, or explanation), your output must contain at least one sentence covering that utterance. Do not skip any speaker's contribution. If someone said something — even briefly — it must appear in the output.

Think of this as: you are a professional meeting scribe who is also an excellent editor. Your job is to take messy, rambling, interleaved conversation and turn it into a clean, readable, well-organized article — without losing a single meaningful thing that was said. You are NOT an abstractor. You are NOT a summarizer. You are a CLEANER — you reorganize and polish, but you keep everything.

---

### What "Too Summarized" Looks Like (DO NOT DO THIS)

Input snippet (200 words of discussion about database migration):
"Speaker 1 says they're considering PostgreSQL 16 because of the JSONB improvements, specifically the new JSON path query syntax. Speaker 2 asks about downtime. Speaker 1 says they tested it on staging and got 47 seconds of downtime with pg_upgrade using --link mode. Speaker 3 mentions they're worried about the replication lag during cutover, specifically with their 3 read replicas. Speaker 1 says they'll need to reconfigure streaming replication after the upgrade. Speaker 2 asks about rollback. Speaker 1 says they'll use pg_dump before the upgrade as a safety net. Speaker 3 asks about the timeline. Speaker 1 says Q2, probably mid-April. Speaker 2 says that conflicts with the product launch. Speaker 1 says they could push to early May. Speaker 3 says they'd prefer after the May 15 launch window."

BAD output (summarized, ~50 words):
"The group discussed migrating to PostgreSQL 16, weighing the JSONB improvements against downtime and replication concerns. They agreed on a Q2 or early May timeline, after the product launch."

GOOD output (refined, ~180 words):
"The discussion turned to PostgreSQL 16 migration. One participant highlighted the JSONB improvements as the primary motivation, specifically the new JSON path query syntax that would simplify their document queries. Another participant raised the question of downtime during the migration. The group reviewed testing results from staging: using `pg_upgrade` with `--link` mode, they measured 47 seconds of downtime — a figure they considered acceptable.

A third participant expressed concern about replication lag during the cutover, noting they currently run 3 read replicas. The group discussed whether streaming replication would need to be reconfigured after the upgrade, and agreed it would. On the question of rollback, one participant proposed using `pg_dump` before the upgrade as a safety net.

The timeline discussion revealed some tension. One participant proposed Q2, specifically mid-April. Another pointed out this conflicts with the product launch. The group discussed pushing to early May instead, and a third participant expressed a preference for scheduling the migration after the May 15 launch window to avoid compounding risk."

Notice: the GOOD output is roughly the same length as the input. It captures every point: the specific PostgreSQL version, the JSON path syntax feature, the 47-second downtime, the --link mode, the 3 read replicas concern, the pg_dump rollback plan, the mid-April proposal, the product launch conflict, the early May alternative, and the May 15 preference. Nothing was dropped.

---

Context: You are given a raw transcription file generated by Whisper from a recorded meeting conversation. Whisper does NOT emit speaker labels — utterances from multiple speakers are interleaved with no markers. The text may also contain noise, broken sentences, filler words, code-switching (especially Chinese-English mixed speech), and recognition errors. The meeting may be a technical discussion, a planning session, a design review, an interview, a brainstorming session, or any other type of conversation.

Task: Read the provided transcription and produce a refined Markdown article that captures the full discussion in comprehensive detail. This is REFINEMENT, not summarization. Preserve every substantive point — restructure for clarity, but never condense or drop information. The cardinal sin is omission.

---

## 1. Content & Structure

### Title
- Start with a single H1 title that captures the core subject of the meeting. Be specific, not generic — "Discussion of Q2 Database Migration Strategy" not "Meeting Notes."
- If the meeting covered multiple major topics, the title should reflect the primary through-line or the most significant topic. If no single topic dominates, use a title that encompasses the scope (e.g., "Q3 Planning: Infra Roadmap, Hiring, and Budget Review").
- Do NOT title it "Meeting Transcription," "Refined Notes," "Discussion Summary," or anything similarly generic.

### Summary Paragraph
- Immediately after the title, include a short summary paragraph (3–6 sentences) that introduces the main themes covered. This paragraph should be a compact overview, not a replacement for the body — the reader should know what topics were discussed, but must read the body for the actual content.
- The summary should mention every major topic section that follows. If the body has five H2 sections, the summary should touch on all five.
- Do NOT put specific data, numbers, decisions, or action items only in the summary — these must be fully developed in the body sections.

### Section Organization
- Organize the body under H2 section headings driven by natural topic shifts in the discussion. A topic shift occurs when the subject matter, context, or focus of the conversation meaningfully changes.
- Use H3 sub-headings within sections when a section covers multiple distinct sub-topics. Do not force H3 headings where the section is already focused on a single coherent topic — a section with only one H3 is a sign that the H3 is probably the H2.
- Within sections, break content into focused paragraphs by topic subtopic — typically 3–8 sentences each. Avoid walls of text (paragraphs over 10 sentences should be split) and avoid one-sentence paragraphs (which fragment the reading experience).
- PREFER MORE PARAGRAPHS OVER FEWER. When in doubt, start a new paragraph. A 20-paragraph section is better than a 5-paragraph section that tries to cram everything into dense blocks.
- Use bullet lists when the speakers genuinely enumerate items: steps in a process, options under consideration, pros and cons of a decision, named tools or technologies, criteria, requirements, risks, open questions. Use prose paragraphs for explanations, narratives, background context, and reasoned arguments.
- Within bullet lists, each item should be substantive — not "Talked about databases" but "Discussed whether to migrate from PostgreSQL 14 to 16, weighing the JSONB performance improvements against the downtime required."
- NEVER collapse a list of discussed items into a single summary sentence. If 7 tools were mentioned, list all 7. If 4 concerns were raised, list all 4. If 3 alternatives were compared, describe all 3.
- When the conversation naturally follows a sequence (e.g., a walkthrough of an architecture, a step-by-step debugging session, a chronological retelling of events), preserve that sequence rather than forcing a topical regroup.

### Topic Grouping Across Time
- If the same topic is discussed, interrupted, and revisited later in the meeting, group all discussion of that topic together in one section. Do not scatter related content across the article just because the conversation jumped around.
- When grouping related discussion, note when the conversation circled back: "Later in the meeting, the group returned to this topic and added that …"

---

## 2. Detail Preservation (Critical — Highest Priority — The Entire Point of This Task)

This is the most important section. The whole reason this prompt exists is to prevent detail loss. Violating these rules produces a bad output. Read each bullet carefully. Re-read them after you finish writing your output and before you submit it.

### Anti-Summarization Rules (Non-Negotiable)
- Do NOT summarize, simplify, compress, or condense the discussion. Cover every meaningful point that was made. If someone spent three minutes explaining a nuanced technical tradeoff, your output should reflect all three minutes of nuance — not a one-sentence gloss.
- If the input contains 10 distinct points about a topic, your output must contain all 10 — even if you think 5 would be "cleaner." Cleanliness is achieved through organization and prose quality, not through deletion.
- CRITICAL TEST: After writing a section, compare it against the relevant portion of the input. If you can point to a substantive claim, example, argument, or detail in the input that is absent from your output, you have failed. Revise.
- SECOND CRITICAL TEST: Count the number of distinct substantive points in the input section and count them in your output section. If your count is less than 75% of the input count, you have summarized instead of refined. Add back the missing points.
- Redundancy in the original transcript (the same person making the same point twice in the same words) should be collapsed to the clearest version — that is the one exception to "keep everything." But if two different people make the same point, or someone makes the same point in two different contexts, keep both.
- When in doubt, KEEP IT. It is always better to include a point that turns out to be minor than to omit a point that turns out to be important. Err on the side of inclusion, never exclusion.

### Specifics and Concrete Details
- Preserve specific examples, anecdotes, numbers, names, dates, file paths, command names, configuration values, version numbers, metrics, benchmarks, URLs, and technical details exactly as discussed. If the input says "we saw a 47% improvement in p99 latency after switching the connection pool from HikariCP 5.0.1 to 5.1.0 with the new keepaliveTimeMs=30000 setting," your output must include all of those specifics — not "they improved latency by changing pool settings."
- Preserve technical terms, proper nouns, product names, library names, frameworks, model names, company names, and specific references exactly — do not generalize them away. Examples of what NOT to do:
  - "CUDA kernel" → "GPU code" ✗ (keep "CUDA kernel")
  - "Redis Cluster with 6 nodes across 3 AZs" → "distributed cache" ✗ (keep the full detail)
  - "We evaluated DVC, LakeFS, and Nessie" → "they looked at several data versioning tools" ✗ (name all three)
  - "The PyTorch FSDP wrapper with HYBRID_SHARD mode" → "distributed training" ✗ (keep the specific configuration)
  - "nginx with the proxy_cache_lock directive" → "caching layer" ✗ (keep the exact directive)

### Numbers, Dates, and Quantitative Data
- Convert spoken numeric expressions to numerals whenever the exact value is clear:
  - "fifty K CNY" → "50K CNY"
  - "three hundred million" → "300 million"
  - "two point five times" → "2.5x"
  - "GPT four" → "GPT-4"
  - "around twenty to thirty percent" → "around 20–30%"
  - "version three point eleven" → "version 3.11"
  - "about five to seven milliseconds" → "about 5–7ms"
  - "Q one of twenty twenty-four" → "Q1 2024"
  - "March fifteenth" → "March 15"
  - "one hundred and twenty three gigabytes" → "123 GB"
- When a number is clearly approximate, preserve the approximation marker: "about 50," "roughly 100," "approximately 200–300," "on the order of 10,000."
- When a number is genuinely uncertain in the transcript (you cannot tell if they said "fifteen" or "fifty"), preserve the ambiguity: "(15 or 50?)" rather than guessing.
- For percentages, use the % sign: "thirty percent" → "30%," not "30 percent."
- For currency, use standard notation: "five hundred dollars" → "$500," "fifty K CNY" → "50K CNY," "two million yen" → "¥2M."

### Process, Tradeoff, and Enumeration Handling
- If the speakers explore a tradeoff, list both (or all) sides explicitly — do not collapse into "they weighed pros and cons."
- If they describe a process step by step, describe each step explicitly — do not write "they walked through the deployment process."
- If they list considerations, criteria, risks, or options, list each one individually — do not write "they discussed several factors."
- If they compare alternatives (A vs B vs C), describe each alternative and the comparison points for each — do not write "they compared a few approaches."
- If the discussion includes a concrete example or case study, recount it fully. Do not write "they gave an example" — write out the example.

### Anti-Pattern: Vague Collapse Language
If you find yourself about to write any of the following, STOP and write out what was actually said instead:
- "and so on"
- "various topics"
- "many things were discussed"
- "they covered different aspects"
- "among other things"
- "to name a few"
- "etc."
- "and similar tools"
- "several approaches"
- "a number of challenges"
- "multiple considerations"
- "in summary"
- "overall, they agreed that …" (without first presenting what was discussed in detail)

### Code, Architecture, and Technical Workflows
- When the conversation discusses code, architecture, or technical workflows, retain the specifics: function names, class names, file paths, command names, configuration keys and values, API endpoints, protocol details, version numbers.
- Use inline code formatting (`backticks`) for: function names (`authenticate_user`), class names (`DatabasePool`), file paths (`/etc/nginx/nginx.conf`), command names (`kubectl`, `git rebase`), configuration keys (`max_connections`), short code snippets or values (`timeout=30s`), environment variable names (`DATABASE_URL`), and API endpoint paths (`/api/v2/users`).
- Use fenced code blocks (```) for: multi-line code examples discussed in the meeting, configuration file excerpts, SQL queries, command sequences, or any code that spans more than one line. Specify the language for syntax highlighting: ```python, ```yaml, ```sql, ```bash, etc.
- When an architectural diagram or system topology is described verbally, render it as a clear textual description with component names and their relationships — do not attempt ASCII art, but do not collapse it into "they described the architecture" either. Write out: "The system has three tiers: an nginx reverse proxy (with SSL termination), a Gunicorn application layer (4 workers, preloaded), and a PostgreSQL 16 primary with one read replica. Redis sits alongside the app layer as a session store and query cache."

---

## 3. Action Items, Decisions, and Commitments

### Decisions
- Explicitly capture every decision the group made, no matter how small. Format as: "**Decision:** …"
- If a decision was conditional or provisional, note that: "**Decision (provisional):** … pending the results of …"
- If the group explicitly chose NOT to do something, capture that too: "**Decision:** Not to adopt … because …"
- Include the reasoning behind each decision when it was discussed. A decision without its rationale is incomplete.

### Action Items
- Capture every action item, task assignment, follow-up, or commitment that emerged from the discussion. Format as: "**Action item:** [Owner] will [task] by [deadline if mentioned]."
- When no owner was specified, write: "**Action item:** [Unassigned] …"
- Action items should be concrete and verifiable — "look into it" is not an action item; "investigate the memory leak in the auth service" is.
- Group action items at the end of the relevant topic section under an "**Action Items**" sub-heading (H3 or H4), not in a single appendix at the end of the article — this keeps each action item close to its context.

### Open Questions
- Capture unresolved questions and uncertainties. Format as: "**Open question:** …"
- If the group deferred a topic to a future meeting, note it: "Deferred to next meeting: …"
- If conflicting views were expressed and not resolved, note that: "No consensus was reached on whether to …"
- If someone promised to gather more information before a decision could be made, capture that.

---

## 4. Tone & Fidelity

### Preserve Voice
- Preserve the original meaning, tone, speaking style, and emotional nuance of the conversation.
- Do not overly formalize the content — retain the conversational and authentic feel of the original meeting. If the speakers were casual and direct, the output should feel casual and direct. If they were formal and precise, the output should reflect that.
- Keep moments of humor, frustration, hesitation, excitement, surprise, or skepticism legible in the prose rather than scrubbing them out. For example:
  - "One participant expressed strong skepticism about the timeline, calling it 'wildly optimistic.'" (Not: "Concerns were raised about the timeline.")
  - "There was a moment of laughter when someone pointed out that the 'temporary fix' from 2019 was still in production." (Not: "It was noted that a temporary fix remained in production.")
- When a speaker uses a metaphor, analogy, or colorful expression, preserve it — it carries meaning and tone. "The monolith is a ball of mud" should stay as "the monolith is a ball of mud," not become "the monolith has architectural issues."

### Emphasis and Intensity
- When a speaker clearly emphasized something, use bold or italics to convey that emphasis: "One participant was **adamant** that the migration must happen before the holiday freeze."
- When the group reached strong consensus, convey it: "There was strong agreement that …" vs "The group leaned toward …"
- When there was disagreement or tension, convey it: "This point drew pushback from another participant, who argued …"
- When someone was uncertain or hedging, convey it: "One participant tentatively suggested … but acknowledged they hadn't tested it."

### Handling Unclear or Ambiguous Segments
- If a sentence or segment is unclear due to transcription quality, handle it on a spectrum rather than always writing "(unclear)":
  - If you can infer the likely meaning with high confidence (>90%), write the inferred content normally without marking it.
  - If you can infer the gist but not the exact wording, write the gist and mark it: "(roughly: …)"
  - If you can only infer the general topic, write: "(Discussion about [topic], details unclear)"
  - If the segment is completely unintelligible, write: "(unclear)"
  - If there is a gap or silence in the recording, write: "(gap in recording)"
- Aim for fewer than 2% of paragraphs to contain uncertainty markers. If you are using them heavily, reconsider whether you are being too conservative in inference.
- Never invent specific details to fill gaps. It is better to write "they discussed database options (details unclear)" than to invent "they discussed whether to use PostgreSQL or MySQL."

### Disagreements and Contradictions
- When speakers disagree, present both (or all) views fairly and completely — do not favor one side or synthesize them into a false consensus.
- Use language that signals disagreement clearly: "One participant argued that …; another pushed back, contending that …; a third suggested a middle ground of …"
- If a speaker contradicted something said earlier (by themselves or someone else), note it: "Later, the same participant walked back this position, saying …"
- If one view clearly prevailed and a decision was made, state that. If the disagreement remained unresolved, state that.

---

## 5. Speaker Handling

### The No-Labels Rule
- Whisper transcription has no speaker labels, and you cannot reliably reconstruct who said what. Even if you detect patterns (sentence length, vocabulary, topic affinity), do not attempt to attribute utterances to individuals.
- Do NOT use labels like "Speaker A / Speaker B," "Person 1 / Person 2," "Participant X," or invent speaker names.
- Do NOT refer to speakers by role unless the content of what they said makes the role unambiguous. For example, if someone says "as the team lead, I think we should …" you can write "the team lead suggested …" But do not infer roles from content alone.
- Do NOT consistently associate a "voice" with a position — vary your phrasing to avoid the reader inferring that there are two specific people debating.

### Third-Person Narration Patterns
- Narrate the discussion in third person. Use a variety of phrases to avoid repetition:
  - "They discussed …"
  - "Both participants …"
  - "One participant noted …"
  - "It was raised that …"
  - "The group considered …"
  - "Another argued …"
  - "Someone brought up …"
  - "The conversation turned to …"
  - "A point was made that …"
  - "There was agreement that …"
  - "Several people voiced concern about …"
  - "One person pushed back, saying …"
  - "The group circled back to …"
  - "It was suggested that …"
  - "A counterpoint was raised: …"
- For clear question-and-answer dynamics, render as "one participant asked whether …; another responded that …" rather than guessing identities.
- For statements that are clearly reactions to a previous point, use: "In response, it was argued that …" or "This prompted a follow-up question about …"
- For back-and-forth exchanges on a specific point, you can group them: "A brief back-and-forth followed: one side argued X; the other countered that Y; the discussion settled on Z."

### Direct Quotation
- When a speaker said something in a particularly striking, precise, or colorful way, you may use a short direct quote: "As one participant put it, 'the current pipeline is held together with duct tape and hope.'"
- Use direct quotes sparingly — no more than 2–3 per article. Overuse undermines the refinement goal.
- Do not use quotation marks for indirect speech or paraphrasing. Only use them for verbatim quotes where you are confident the transcription captured the exact words.
- If you are unsure of the exact wording but the sentiment is striking, paraphrase without quotation marks: "One participant described the current pipeline as barely functional and overdue for replacement."

---

## 6. Noise Removal

### Remove
- Filler words and verbal tics:
  - "um," "uh," "er," "ah," "mm"
  - "like" (as filler, not as comparison: keep "languages like Rust" but remove "it was, like, really slow")
  - "you know," "I mean," "kind of," "sort of," "basically," "literally," "actually" (when filler, not substantive)
  - "right" (when used as a filler/agreement marker, not when it means "correct" in context)
  - "yeah," "yep," "uh-huh," "mm-hmm" (when used as backchanneling/agreement markers without content)
  - "so" (at the start of a sentence when used as a discourse marker, not when part of a "so that" construction)
  - "well" (at the start of a response when used as a hedge)
  - "I think" / "I feel like" (when used as a hedge, not when expressing actual belief: keep "I think the bug is in the parser" but remove "I think we should, you know, like, move on")
- False starts and self-corrections — keep only the corrected, complete version. "We should use — actually, no, we should consider using Redis" → "We should consider using Redis."
- Repeated words and stutters: "the the the database" → "the database."
- Repeated phrases where the same person restates the same point in the same words — collapse to the clearest version.
- Obviously garbled fragments and Whisper recognition errors with no recoverable meaning — these sound like random syllables or nonsensical word sequences.

### Keep
- Substantive uses of "yeah," "right," "exactly," "no," "yes" when they convey real agreement, disagreement, or are part of a meaningful exchange. "One participant asked, 'Is this the right approach?' Another responded, 'Exactly — that's what I'm saying.'"
- "I think" or "I believe" when part of a substantive claim: "I think the memory leak is in the connection pool" — keep this, as it signals tentative/uncertain knowledge.
- Hedging language that conveys genuine uncertainty: "It might be a threading issue, but I haven't verified."
- Discourse markers that serve a structural purpose: "First, … Second, …" (keep for enumeration); "However, …" / "On the other hand, …" (keep for contrast).
- "So" when used in a "so that" construction or to introduce a conclusion derived from preceding reasoning.

### Important: Noise Removal Must Not Remove Information
- Do not remove information; only remove noise. If you are unsure whether something is noise or substance, keep it.
- A good test: if removing a word or phrase would change or lose meaning, keep it. If removing it makes the text cleaner without any loss, remove it.

---

## 7. Reorganization

### Topical Grouping
- Merge fragmented dialogue across the transcript into coherent topical paragraphs — do NOT preserve the original chronological order if topics are scattered. Group all discussion of the same topic together even if it was revisited later.
- When the group circles back to a topic, either integrate the later discussion into the earlier section (with a note like "Later in the meeting, the group returned to this topic and …") or, if the later discussion is extensive, create a separate sub-section for it.
- Within each topic, follow the natural logical flow of the argument or explanation rather than the order utterances happened to appear. Build from context → problem → options → analysis → decision (or whatever flow best fits the discussion).

### Tangents and Off-Topic Discussion
- If the conversation includes a brief tangent that is genuinely off-topic (e.g., a 30-second digression about weekend plans in the middle of a technical discussion), you may either omit it or place it in a brief footnote-style paragraph at the end of the relevant section.
- If the tangent is long enough to contain substance (e.g., an unexpected but interesting side discussion about a related project), give it its own section rather than omitting it.
- Use your judgment: a tangent about someone's cat is noise; a tangent about a related technical approach that might be useful later is content.

### Transitions
- Add brief transitional phrases between major topic shifts to help the reader follow the structure: "The discussion then shifted to …," "Next, the group turned their attention to …," "Building on the previous topic, they then considered …"
- Do not overuse transitions — one per major topic shift is sufficient. Do not add transitions between sub-topics within the same section unless the connection is non-obvious.

---

## 8. Language

### Output Language
- Always output in fluent, natural English regardless of the source language.
- If the source is Chinese (or any other language), translate while refining — preserve meaning, nuance, technical terminology, and emotional register. Avoid stiff, word-for-word translation.
- The goal is for the output to read as if the meeting was originally conducted in English by fluent speakers — not as if it was translated.

### Code-Switching / Mixed-Language Segments
- When the transcript contains mixed-language segments (e.g., Chinese discussion that drops in English technical terms, or vice versa), retain all technical terms in their canonical form — do not translate them.
  - Example: "我们用的是 Kubernetes cluster with Istio service mesh" → "They are using a Kubernetes cluster with Istio service mesh."
  - Example: "这个 function 的 complexity 太高了" → "This function's complexity is too high."
- When a Chinese term or concept has no natural English equivalent, keep it in pinyin with a brief parenthetical explanation on first use: "They discussed guanxi (关系, relationship networks) as a factor."
- When a proper noun or company name is commonly used in Chinese, use its standard English form if one exists: "字节跳动" → "ByteDance"; "腾讯" → "Tencent"; "阿里巴巴" → "Alibaba." If there is no standard English form, transliterate.

### Technical Terminology
- Keep proper nouns, brand names, and technical terms in their canonical form. Use:
  - "CUDA" not "kuda"
  - "GitHub" not "github" (unless it's a command: `git push`)
  - "PyTorch" not "pytorch"
  - "TypeScript" not "typescript"
  - "Redis" not "redis" (unless it's a command: `redis-cli`)
- For Chinese company names, use their commonly used English form when one exists (e.g., "ByteDance," "Meituan," "Xiaomi"). Otherwise, transliterate (e.g., "Kuaishou," not "快手").
- For product names, use the official capitalization: "iPhone," "WeChat," "macOS," "Windows."

### Terminology Consistency
- Use the same term consistently throughout the article. If the conversation uses "auth service" and "authentication service" interchangeably, pick one and stick with it — but note the variation on first occurrence: "the auth service (also referred to as the authentication service) …"

---

## 9. Technical Formatting

### Inline Code
Use `backticks` for:
- Function and method names: `authenticate_user()`, `DatabasePool.__init__()`
- Class and type names: `DatabasePool`, `RequestHandler`
- Variable and parameter names: `max_retries`, `connection_timeout`
- File paths: `/etc/nginx/sites-enabled/default`, `src/auth/handlers.py`
- Directory paths: `/var/log/nginx/`, `~/.config/`
- Command names: `kubectl`, `git rebase`, `docker compose`, `systemctl`
- Configuration keys: `max_connections`, `proxy_read_timeout`
- Short configuration values: `timeout=30s`, `replicas: 3`
- Environment variable names: `DATABASE_URL`, `NODE_ENV`
- API endpoint paths: `/api/v2/users`, `POST /webhooks/github`
- Protocol and format names when specific: `HTTP/2`, `gRPC`, `WebSocket`
- Port numbers: port `5432`, port `3000`
- Short code expressions: `x is None`, `if err != nil`, `len(items) > 0`

### Fenced Code Blocks
Use fenced code blocks with language specifiers for:
- Multi-line code examples: ```python … ```
- Configuration file excerpts: ```yaml … ```, ```ini … ```, ```toml … ```
- SQL queries: ```sql … ```
- Shell command sequences: ```bash … ```
- JSON output or schemas: ```json … ```
- Log output excerpts: ```log … ```
- Diff output: ```diff … ```

### Architecture and Diagrams
- When participants describe an architecture verbally, render it as clear descriptive prose with component names and relationships: "The system consists of: an nginx reverse proxy handling SSL termination; a Gunicorn application server with 4 pre-forked workers; a PostgreSQL 16 primary database with one read replica; and a Redis instance for session storage and query caching. The app server communicates with PostgreSQL over a private VPC subnet, while client traffic comes through CloudFront → nginx."
- Do NOT try to create ASCII art diagrams — they render poorly. Descriptive prose is better.
- Use consistent component names throughout. If a component is called "API Gateway" in one section, don't call it "gateway service" in another.

---

## 10. Output Format

### Strict Rules
- Output ONLY valid Markdown content.
- Do NOT include any preamble ("Here is the refined article…," "Below is the polished meeting notes…," etc.), closing remarks ("I hope this helps," "Let me know if you need changes," etc.), metadata blocks, or commentary outside the article itself.
- Start the response directly with the H1 title — that is the very first character of your output.
- End the response after the last substantive paragraph — no signature, no "---" separator, no trailing commentary.

### Markdown Conventions
- Use ATX-style headings (with `#`), not setext-style (underlined with `=` or `-`).
- Use `- ` for unordered lists, not `* `.
- Use `1. ` for ordered lists.
- Use `**bold**` for emphasis, decisions, and key conclusions.
- Use `*italic*` for light emphasis, book titles, and introduced terms.
- Use `> ` blockquotes sparingly — reserve for direct quotations from participants that are striking enough to highlight.
- Use `---` horizontal rules only to separate major thematic divisions when the meeting covered truly distinct domains (e.g., a meeting that covered both a technical review and a hiring discussion). Do not overuse.
- Use `[text](url)` for links when URLs are mentioned. If only a domain or service name is mentioned without a specific URL, do not link it.
- Tables are acceptable when the discussion involves structured comparison data: pros/cons, feature matrices, benchmark results, timeline milestones. Use sparingly and only when a table genuinely improves readability over prose or a list.

### Final Quality Check (MANDATORY — Do This Before Submitting)

Before finalizing, perform these checks IN ORDER:
1. **Length check**: Count the approximate word count of your output. Compare to the input word count. If your output is less than 85% of the input, you have summarized too aggressively. Go back and add the missing detail.
2. **Coverage check**: Scan through the input paragraph by paragraph. For each paragraph, verify that the content appears in your output. If any substantive paragraph is missing, add it.
3. **Specificity check**: Scan your output for any instance of "various," "several," "multiple," "a number of," "and so on," "etc.," "among other things," "they discussed," "they covered," or "they talked about" — each of these is a red flag that you collapsed detail. Replace each one with the actual content.
4. Is every substantive point from the input present in the output?
5. Are all numbers, names, dates, and technical specifics preserved exactly?
6. Are all decisions and action items captured explicitly?
7. Are there no vague collapse phrases?
8. Are speaker labels entirely absent?
9. Is the tone authentic to the original conversation?
10. Does the output start directly with the H1 title, with no preamble?
"""


def _read_input(path):
    abs_path = os.path.abspath(path)
    if not os.path.isfile(abs_path):
        print(f"Error: file not found: {abs_path}")
        sys.exit(1)
    with open(abs_path, "r", encoding="utf-8") as f:
        return abs_path, f.read()


def _output_path(input_path):
    root, _ = os.path.splitext(input_path)
    return root + ".md"


def _build_prompt(transcript):
    return f"{REFINE_RULE}\n\n---\n\nTranscription:\n\n{transcript}"


def _stream_to_stdout(prompt, model, debug):
    chunks = []
    started = time.monotonic()
    first_chunk_at = None
    for text in stream_openrouter_api(prompt, model=model, debug=debug):
        if first_chunk_at is None:
            first_chunk_at = time.monotonic()
            print(
                f"[refine] first token in {first_chunk_at - started:.1f}s, streaming...\n"
            )
            print("---")
        sys.stdout.write(text)
        sys.stdout.flush()
        chunks.append(text)
    elapsed = time.monotonic() - started
    if first_chunk_at is None:
        print("[refine] warning: stream ended with no content")
    else:
        print("\n---")
    return "".join(chunks), elapsed


def main():
    parser = argparse.ArgumentParser(
        description="Refine a Whisper transcription txt file into a polished Markdown article via OpenRouter (streaming)."
    )
    parser.add_argument("input_file", help="Path to the .txt transcription file")
    parser.add_argument(
        "--model",
        default="deepseek/deepseek-v4-flash",
        help="OpenRouter model (default: deepseek/deepseek-v4-flash)",
    )
    parser.add_argument("--debug", action="store_true")
    args = parser.parse_args()

    input_path, transcript = _read_input(args.input_file)
    output_path = _output_path(input_path)
    prompt = _build_prompt(transcript)

    print(f"[refine] input={input_path} ({len(transcript)} chars)")
    print(f"[refine] output={output_path}")
    print(f"[refine] model={args.model}")
    print("[refine] connecting to OpenRouter...")

    refined, elapsed = _stream_to_stdout(prompt, args.model, args.debug)

    if not refined:
        print("[refine] no content received; not writing output file")
        sys.exit(1)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(refined)

    print(f"[refine] wrote {len(refined)} chars to {output_path} in {elapsed:.1f}s")
