port: 7890
socks-port: 7891
mixed-port: 7892
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
experimental:
  ignore-resolve-fail: true

dns:
  enable: true
  # ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 119.29.29.29
    - 223.5.5.5
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"

# Clash for Windows
cfw-latency-timeout: 3000
cfw-latency-url: http://cp.cloudflare.com/generate_204
cfw-conn-break-strategy: true

# Clash for Android
clash-for-android:
  ui-subtitle-pattern: '[\u4e00-\u9fa5]{2,4}'

# Stash
url-rewrite:
  - ^https?:\/\/(www.)?(g|google)\.cn https://www.google.com 302
  - ^https?:\/\/(ditu|maps).google\.cn https://maps.google.com 302

proxies:
  - name: My SS Proxy 1
    type: ss
    server: 143.198.0.0
    port: 1479
    cipher: chacha20-ietf-poly1305
    password: rK8Cai1SrW9QbDITWcvGIK
    udp: true
    plugin: ""
    plugin-opts: {}
  - name: My SS Proxy 2
    type: ss
    server: 143.198.0.0
    port: 1479
    cipher: chacha20-ietf-poly1305
    password: rK8Cai1SrW9QbDITWcvGIK
    udp: true
    plugin: ""
    plugin-opts: {}

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - My SS Proxy 1
      - My SS Proxy 2

rule-providers:
  Global:
    type: http
    behavior: classical
    path: ./Rules/Global.yaml
    url: https://cdn.jsdmirror.cn/gh/tututo/RuleFiles@main/Clash/Provider/Proxy.yaml
    interval: 1440
  China:
    type: http
    behavior: classical
    path: ./Rules/China.yaml
    url: https://cdn.jsdmirror.cn/gh/tututo/RuleFiles@main/Clash/Provider/Domestic.yaml
    interval: 1440
  ChinaIP:
    type: http
    behavior: classical
    path: ./Rules/ChinaIP.yaml
    url: https://cdn.jsdmirror.cn/gh/tututo/RuleFiles@main/Clash/Provider/Domestic%20IPs.yaml
    interval: 86400
  LAN:
    type: http
    behavior: classical
    path: ./Rules/LAN.yaml
    url: https://cdn.jsdmirror.cn/gh/tututo/RuleFiles@main/Clash/Provider/LAN.yaml
    interval: 86400


rules:
  - DOMAIN-SUFFIX,linkedin.com,Proxy
  - DOMAIN-SUFFIX,deepseek.com,Proxy
  - DOMAIN-SUFFIX,quora.com,Proxy
  - DOMAIN-SUFFIX,binance.com,Proxy
  - DOMAIN-SUFFIX,scholar.google.com,Proxy
  - DOMAIN-SUFFIX,gemini.google.com,Proxy
  - DOMAIN-SUFFIX,aistudio.google.com,Proxy
  - DOMAIN-SUFFIX,googleapis.com,Proxy
  - DOMAIN-SUFFIX,tiktokv.com,Proxy
  - DOMAIN-SUFFIX,claude.ai,Proxy
  - DOMAIN-SUFFIX,chatgpt.com,Proxy
  - DOMAIN-SUFFIX,openrouter.ai,Proxy
  - DOMAIN-SUFFIX,chatboxai.app,Proxy
  - DOMAIN-SUFFIX,kimi.com,Proxy
  - DOMAIN-SUFFIX,x.ai,Proxy
  - DOMAIN-SUFFIX,openai.com,Proxy
  - DOMAIN-SUFFIX,anthropic.com,Proxy
  - DOMAIN-SUFFIX,grok.com,Proxy
  - DOMAIN-SUFFIX,cdn.grok.com,Proxy
  - DOMAIN-SUFFIX,x.com,Proxy
  - RULE-SET,Global,Proxy
  - RULE-SET,China,DIRECT
  - RULE-SET,ChinaIP,DIRECT
  - DOMAIN-SUFFIX,local,DIRECT
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,17.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,100.64.0.0/10,DIRECT,no-resolve
  - IP-CIDR,127.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,224.0.0.0/4,DIRECT,no-resolve
  - IP-CIDR6,fe80::/10,DIRECT,no-resolve
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
